CREATE DATABASE BD08_EX04;

CREATE TABLE FUNCIONARIO(
	codFunc INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	codFilial INT NOT NULL,
	nomeFunc varchar(200) NOT NULL 
);

CREATE TABLE FILIAL(
	CodFilial INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	cidade varchar(50) NOT NULL 
);

CREATE TABLE PAGAMENTO(
	codPagamento INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	codComp INT,
	codFunc INT,
	codEve INT,
	dtPagamento DATE NOT NULL,
	valorPagamento FLOAT NOT NULL 
)

CREATE TABLE EVENTO(
	codEvento INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	tipoEvento varchar(20)
)


CREATE TABLE COMPETENCIA(
	codComp INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	mesComp INT NOT NULL,
	anoComp INT NOT NULL,
	nroperiodo DATE NOT NULL
)

ALTER TABLE PAGAMENTO 
ADD CONSTRAINT FK_PAG_COMP FOREIGN KEY (codComp) REFERENCES COMPETENCIA(codComp)

ALTER TABLE PAGAMENTO 
ADD CONSTRAINT FK_PAG_FUNC FOREIGN KEY (codFunc) REFERENCES FUNCIONARIO(codFunc)

ALTER TABLE PAGAMENTO 
ADD CONSTRAINT FK_PAG_EVE FOREIGN KEY (codEve) REFERENCES EVENTO(codEvento)

ALTER TABLE FUNCIONARIO
ADD CONSTRAINT FK_FUNC_FIL FOREIGN KEY (CodFilial) REFERENCES FILIAL(CodFilial)







