CREATE DATABASE livrariaJaLi

CREATE TABLE dbo.AREA(
	CODIGO int NOT NULL,
	DESCRICAO varchar(250) NULL,
PRIMARY KEY CLUSTERED 
(
	CODIGO ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON PRIMARY
) ON PRIMARY
GO

CREATE TABLE dbo.AUTOR(
	CODIGO_AUTOR int NOT NULL,
	NOME varchar(250) NULL,
	TELEFONE varchar(15) NULL,
	ENDERECO varchar(250) NULL,
PRIMARY KEY CLUSTERED 
(
	CODIGO_AUTOR ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON PRIMARY
) ON PRIMARY
GO

CREATE TABLE dbo.CLIENTE(
	CODIGO_CLIENTE int NOT NULL,
	NOME varchar(250) NULL,
	TELEFONE varchar(15) NULL,
	ENDERECO varchar(250) NULL,
	TIPO varchar(50) NULL,
PRIMARY KEY CLUSTERED 
(
	CODIGO_CLIENTE ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON PRIMARY
) ON PRIMARY
GO

CREATE TABLE dbo.EDITORA(
	CODIGO_EDITORA int NOT NULL,
	NOME varchar(250) NULL,
	TELEFONE varchar(15) NULL,
	ENDERECO varchar(250) NULL,
PRIMARY KEY CLUSTERED 
(
	CODIGO_EDITORA ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON PRIMARY
) ON PRIMARY
GO


CREATE TABLE dbo.EMPRESTA(
	CODIGO_EMPRESTA int AUTO_INCREMENT NOT NULL,
	CODIGO_CLIENTE int NULL,
	CODIGO_EXEMPLAR int NULL,
	DATA_EMPRESTA date NULL,
PRIMARY KEY CLUSTERED 
(
	CODIGO_EMPRESTA ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON PRIMARY
) ON PRIMARY
GO

CREATE TABLE dbo.EXEMPLAR(
	CODIGO_EXEMPLAR int NOT NULL,
PRIMARY KEY CLUSTERED 
(
	CODIGO_EXEMPLAR ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON PRIMARY
) ON PRIMARY
GO

CREATE TABLE dbo.PALAVRA_CHAVE(
	CODIGO_PALAVRA int NOT NULL,
	DESCRICAO varchar(250) NULL,
PRIMARY KEY CLUSTERED 
(
	CODIGO_PALAVRA ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON PRIMARY
) ON PRIMARY
GO

CREATE TABLE dbo.TITULO(
	CODIGO_TITULO int NOT NULL,
	CODIGO_AREA int NULL,
	CODIGO_PALAVRA int NULL,
	CODIGO_EDITORA int NOT NULL,
	CODIGO_AUTOR int NOT NULL,
	CODIGO_EXEMPLAR int NOT NULL,
	NOME varchar(250) NULL,
PRIMARY KEY CLUSTERED 
(
	CODIGO_TITULO ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON PRIMARY
) ON PRIMARY
GO

CREATE TABLE EMPRESTA(
	CODIGO_EMPRESTA INT PRIMARY KEY IDENTITY,
	CODIGO_CLIENTE INT,
	CODIGO_EXEMPLAR INT,
	DATA_EMPRESTA DATE,
	CONSTRAINT FK_CODIGO_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE),
	CONSTRAINT FK_CODIGO_EXEMPLAR_CLI FOREIGN KEY (CODIGO_EXEMPLAR) REFERENCES EXEMPLAR(CODIGO_EXEMPLAR)
)

ALTER TABLE dbo.TITULO  WITH CHECK ADD  CONSTRAINT FK_CODIGO_AREA FOREIGN KEY(CODIGO_AREA)
REFERENCES dbo.AREA (CODIGO)
GO

ALTER TABLE dbo.TITULO CHECK CONSTRAINT FK_CODIGO_AREA
GO

ALTER TABLE dbo.TITULO  WITH CHECK ADD  CONSTRAINT FK_CODIGO_AUTOR FOREIGN KEY(CODIGO_AUTOR)
REFERENCES dbo.AUTOR (CODIGO_AUTOR)
GO

ALTER TABLE dbo.TITULO CHECK CONSTRAINT FK_CODIGO_AUTOR
GO

ALTER TABLE dbo.TITULO  WITH CHECK ADD  CONSTRAINT FK_CODIGO_EDITORA FOREIGN KEY(CODIGO_EDITORA)
REFERENCES dbo.EDITORA (CODIGO_EDITORA)
GO

ALTER TABLE dbo.TITULO CHECK CONSTRAINT FK_CODIGO_EDITORA
GO

ALTER TABLE dbo.TITULO  WITH CHECK ADD  CONSTRAINT FK_CODIGO_EXEMPLAR FOREIGN KEY(CODIGO_EXEMPLAR)
REFERENCES dbo.EXEMPLAR (CODIGO_EXEMPLAR)
GO

ALTER TABLE dbo.TITULO CHECK CONSTRAINT FK_CODIGO_EXEMPLAR
GO

ALTER TABLE dbo.TITULO  WITH CHECK ADD  CONSTRAINT FK_PALAVRA_CHAVE FOREIGN KEY(CODIGO_PALAVRA)
REFERENCES dbo.PALAVRA_CHAVE (CODIGO_PALAVRA)
GO

ALTER TABLE dbo.TITULO CHECK CONSTRAINT FK_PALAVRA_CHAVE
GO

ALTER TABLE dbo.EMPRESTA  WITH CHECK ADD  CONSTRAINT FK_CODIGO_CLIENTE FOREIGN KEY(CODIGO_CLIENTE)
REFERENCES dbo.CLIENTE (CODIGO_CLIENTE)
GO

ALTER TABLE dbo.EMPRESTA CHECK CONSTRAINT FK_CODIGO_CLIENTE
GO

ALTER TABLE dbo.EMPRESTA  WITH CHECK ADD  CONSTRAINT FK_CODIGO_EXEMPLAR_CLI FOREIGN KEY(CODIGO_EXEMPLAR)
REFERENCES dbo.EXEMPLAR (CODIGO_EXEMPLAR)
GO

ALTER TABLE dbo.EMPRESTA CHECK CONSTRAINT FK_CODIGO_EXEMPLAR_CLI
GO
