CREATE TABLE DEPARTAMENTO(
codDep int PRIMARY KEY NOT NULL,
nomeDep varchar(100)
)

CREATE TABLE MAQUINA(
codMaq int PRIMARY KEY,
nomeMaq varchar(100),
codDep int
)

CREATE TABLE TRABALHA(
codTrab int PRIMARY KEY AUTO_INCREMENT,
qtdHoras float,
codMaq int,
codEmpregado int
)

CREATE TABLE EMPREGADO(
codEmpregado int PRIMARY KEY NOT NULL,
nomeEmpregado varchar(200),
telEmpregado varchar(14),
endEmpregado varchar(200),
codDep int
)

CREATE TABLE DEPENDENTE(
codDependente int PRIMARY KEY,
nomeDependente varchar(200),
codEmpregado int
)


ALTER TABLE MAQUINA
ADD CONSTRAINT FK_DEP_MAQ FOREIGN KEY (codDep) REFERENCES DEPARTAMENTO(codDep)

ALTER TABLE EMPREGADO
ADD CONSTRAINT FK_DEP_EMP FOREIGN KEY (codDep) REFERENCES DEPARTAMENTO(codDep)

ALTER TABLE TRABALHA
ADD CONSTRAINT FK_MAQ_TRAB FOREIGN KEY (codMaq) REFERENCES MAQUINA(codMaq)

ALTER TABLE TRABALHA
ADD CONSTRAINT FK_EMP_TRAB FOREIGN KEY (codEmpregado) REFERENCES EMPREGADO(codEmpregado)

ALTER TABLE DEPENDENTE
ADD CONSTRAINT FK_EMP_DEPENDENTE FOREIGN KEY (codEmpregado) REFERENCES EMPREGADO(codEmpregado)

